version: '3.8'

services:
  # PostgreSQL 16 Database
  postgres:
    image: postgres:16-alpine
    container_name: qcollector_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-qcollector_db}
      POSTGRES_USER: ${POSTGRES_USER:-qcollector}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_secure_password_here}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - q-collector-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-qcollector} -d ${POSTGRES_DB:-qcollector_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO Object Storage (S3-compatible)
  minio:
    image: minio/minio:latest
    container_name: qcollector_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-your_minio_password_here}
    ports:
      - "${MINIO_PORT:-9000}:9000"      # API port
      - "${MINIO_CONSOLE_PORT:-9001}:9001"   # Console port
    volumes:
      - minio_data:/data
    networks:
      - q-collector-network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 5

  # Redis 7 Cache & Session Store
  redis:
    image: redis:7-alpine
    container_name: qcollector_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - q-collector-network
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-your_redis_password_here}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Backend Service (Node.js 20)
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    container_name: qcollector_api
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${API_PORT:-5000}
      # Database Configuration
      DATABASE_URL: postgresql://${POSTGRES_USER:-qcollector}:${POSTGRES_PASSWORD:-your_secure_password_here}@postgres:5432/${POSTGRES_DB:-qcollector_db}
      # Redis Configuration
      REDIS_URL: redis://:${REDIS_PASSWORD:-your_redis_password_here}@redis:6379
      # MinIO Configuration
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: ${MINIO_USE_SSL:-false}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-your_minio_password_here}
      MINIO_BUCKET: ${MINIO_BUCKET:-qcollector}
      # Security Configuration
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_key_here_minimum_32_characters}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-15m}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-your_32_byte_hex_encryption_key_here}
      # CORS Configuration
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "${API_PORT:-5000}:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/logs:/app/logs
    networks:
      - q-collector-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PgAdmin for Database Management (Development Only)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: qcollector_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@qcollector.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-pgadmin_password}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - q-collector-network
    depends_on:
      - postgres
    profiles:
      - development

  # Frontend Development service
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: qcollector_frontend_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/build
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
      - REACT_APP_API_URL=http://localhost:5000/api/v1
    profiles:
      - dev
    networks:
      - q-collector-network
    restart: unless-stopped
    depends_on:
      - api

  # Frontend Production service
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qcollector_frontend_prod
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api/v1
    profiles:
      - prod
    networks:
      - q-collector-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - api

  # Nginx Reverse Proxy (Production Only)
  nginx:
    image: nginx:alpine
    container_name: qcollector_nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./backend/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build:/usr/share/nginx/html:ro
    networks:
      - q-collector-network
    depends_on:
      - api
    profiles:
      - prod

networks:
  q-collector-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
  node_modules_cache:
    driver: local